### ISSUE TITLE
Revised Main Menu Layout

### ISSUE THREAD

**Issue by BrianErikson** [BrianErikson/PushLocal-Android#2]
Pack all of the functionality into one or two menus.
Should have the following functionality:
- Discovery button
- List to show discovered, connected, and saved devices (all at the same time)

Item List
- Gray out ListItem if the device is disconnected and offline, but saved
- Red indicator light if the item is discovered but not synced
- Green indicator light if the item is synced and discovered
- Saved devices should be at the top of the list

**Comment by nphelpsiv** [comment]
![pushlocalui](https://cloud.githubusercontent.com/assets/11506940/10118798/340ba9b4-643f-11e5-80d7-9bad73171381.png)

**Comment by BrianErikson** [comment]
Closed on 6330725e894e74fd23499497f6423821c6ac73fd
